name: 기능 요청
description: 새로운 기능 개발을 위한 이슈
title: "[Feature] 기능 이름"
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      placeholder: ex) 플레이어 점프 기능
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 기능 설명
      placeholder: 어떤 동작인지 간단히 설명해주세요
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: 예상 클래스 / 메서드
      placeholder: 클래스명, 주요 책임 등 (선택)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 확인 사항
      options:
        - label: 중복된 기능이 아닙니다
